### ISSUE TITLE
触摸板手势问题

### ISSUE THREAD

**Issue by chenhaoo0** [0xHJK/XPS13-9360-i5-8250U-macOS#10]
最多只有两指手势，三指四指全都没用，是驱动问题吗

**Comment by 0xHJK** [comment]
在系统偏好里面设置过吗？
三指四指都是支持的，虽然因为触控板比较小不是很好用，但手势都是支持的

**Comment by chenhaoo0** [comment]
系统里三指四指的手势都打勾了，但是操作起来好像最多只能识别两指，用三指四指跟两指一样只能翻网页

**Comment by 0xHJK** [comment]
那你试试重新安装一下触控板驱动吧

**Comment by chenhaoo0** [comment]
四指能识别了，只有launchpad打开关闭手势识别不了

**Comment by 0xHJK** [comment]
Launchpad手势可以识别的，但是因为触控板太小了，识别率不高，使用起来也不太方便

**Comment by chenhaoo0** [comment]
原来是这样，那我应该没问题了，别的都正常，感谢大神🙏

**Comment by 0xHJK** [comment]
不客气~我也是学习了别人的经验总结了一下
