### ISSUE TITLE
耳机声音问题

### ISSUE THREAD

**Issue by 4456Dio** [0xHJK/XPS13-9360-i5-8250U-macOS#11]
你好，非常感谢你的教程，我扬声器声音正常，但是插入耳机后就没有声音了，插入的一瞬间有声音，之后就没有了。按照你帖子里面处理问题了，但是还是没有解决。也按照你帖子里面俩问题的处理方式进行处理了，可能是我处理方法不太对，最后也没有起作用，我想问一下具体的处理方法。

**Comment by 4456Dio** [comment]
我不太清楚我重建有没有重建正确，而且我不太清楚layout和AppleALC的用法，所以不敢确定自己对于这两种方法有没有操作正确

**Comment by 0xHJK** [comment]
你试试这两种方式：
第一种：
- 删除`/Library/Extensions/AppleHDA_ALC256.kext`，然后用kext wizard重建缓存
- 设置启动参数`alcid=11`，可以在`config.plist`中设置，也可以在启动时设置

第二种：
- 删除`/Volumes/EFI/EFI/CLOVER/kexts/Other/AppleALC.kext`
- 运行`bash XPS9360.sh --patch-hda`
- 设置启动参数`alcid=2`，可以在`config.plist`中设置，也可以在启动时设置

我用的是第一种，你可以都试试看

**Comment by 4456Dio** [comment]
我今天上午尝试的用ALCplugfix来修的，修完了确实有声音了，可以切换使用了，但是有个小缺点，就是会有白噪音。不算很完美。

**Comment by 4456Dio** [comment]
其他碰到的问题也交流一下吧，我一开始想单盘双系统，在不动win10的情况下装mac，但是不能格式化为APFS，会显示格式化失败未知错误-110，如果格式化为macos日志就会在你重启安装的时候显示不能加载安装器资源（应该是格式化为APFS失败照成的）
所以只能把整改盘格式化先装mac再装win。
用usb连iPhone是可以连iPhone热点的，这样可以不完美解决上网问题

**Comment by 0xHJK** [comment]
@4456Dio 感谢提供的信息，你说的ALCplugfix是这个吗https://github.com/athlonreg/AppleALC-ALCPlugFix

**Comment by 4456Dio** [comment]
https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html
这里的这个讲得更仔细，但是我尝试用这个方法修复杂音问题还是没能成功，因为有几步确实看不懂。

**Comment by 0xHJK** [comment]
更新了耳机声音解决办法，见README.md
