### ISSUE TITLE
系统支持升级吗？

### ISSUE THREAD

**Issue by supergua** [0xHJK/XPS13-9360-i5-8250U-macOS#15]
系统支持直接升级吗？
还是每次升级都得重装系统？重装驱动？

**Comment by elisir80** [comment]
I upgraded from 10.14.3 to 10.14.4 without any kind of issue

**Comment by supergua** [comment]
> I upgraded from 10.14.3 to 10.14.4 without any kind of issue

is your xps USB-C port running right? support hotplugin?

**Comment by 0xHJK** [comment]
有时候升级没问题，有时候会有问题，建议慎重升级，升级前做好备份

一般不需要重装系统，但是有时候会需要更新EFI和驱动
