### ISSUE TITLE
xps9360同配置i5 耳机无声

### ISSUE THREAD

**Issue by AmourHah** [0xHJK/XPS13-9360-i5-8250U-macOS#2]
分别使用您的和the blackvoid的efi重装，皆无法使用，参考后者的 您的布丁命令好像写错了，应该是--patch-hda ，但我这边还是解决不了耳机无声

**Comment by 0xHJK** [comment]
多谢指正，刚刚改过来了。可以参考一下https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/ 中关于【Q. Audio is not working. How to fix?】的回答

**Comment by AmourHah** [comment]
enen 通过ALCPlugFix解决了

**Comment by YipengChen** [comment]
> enen 通过ALCPlugFix解决了

你好，我也碰到耳机没声音的问题，想请教下具体是怎么解决的？
