### ISSUE TITLE
Imessage 和 FaceTime 不能激活

### ISSUE THREAD

**Issue by 1194117884** [0xHJK/XPS13-9360-i5-8250U-macOS#21]
imessage 和 facetime 使用时

错误！
激活时出错。请再试一次。

**Comment by 0xHJK** [comment]
参考https://github.com/0xHJK/XPS13-9360-i5-8250U-macOS#%E8%A7%A3%E5%86%B3%E6%97%A0%E6%B3%95%E8%BF%9E%E6%8E%A5app-store%E7%9A%84%E5%8A%9E%E6%B3%95

**Comment by 1194117884** [comment]
已解决！
