### ISSUE TITLE
睡眠唤醒问题

### ISSUE THREAD

**Issue by JasonJe** [0xHJK/XPS13-9360-i5-8250U-macOS#29]
求教一下，同样
型号配置的机器，安装了10.15.5版本的系统。
进行睡眠的话，立即点击鼠标或者键盘，能马上回到登录界面；但是长时间唤醒，屏幕黑屏，键盘背光能亮，只能长按电源键强制关机重启，开机后的崩溃报告以及日志没有详细说明是因为什么原因导致的，请问版主有遇到过吗？

**Comment by nn-666** [comment]
的确出现过这个问题，但出现的频率不高
