### ISSUE TITLE
睡眠问题和OC引导BUG

### ISSUE THREAD

**Issue by go-david** [0xHJK/XPS13-9360-i5-8250U-macOS#31]
OC的config.plist多了个voodooinput 会导致无法引导成功
另外，我的机器睡眠有问题，睡眠之后再也无法唤醒，只能强制重启

**Comment by nn-666** [comment]
---XPS13-9360   i5-8250u  HD620--
机器睡眠无法唤醒这个问题我也有遇到，不过是Windows2004上😹，macOS却没有遇到这个问题。

go-david <notifications@github.com> 于2020年8月1日周六 下午5:11写道：
