### ISSUE TITLE
进不去系统

### ISSUE THREAD

**Issue by Lumiaqian** [0xHJK/XPS13-9360-i5-8250U-macOS#4]
一样的配置，换了你的EFI进不去，很尴尬

**Comment by 0xHJK** [comment]
BIOS版本一样吗，BIOS的设置是否已修改？
然后在启动参数后面加`-v`看一下是哪里卡住了

**Comment by Lumiaqian** [comment]
是开机比较慢，而且外接usb鼠标没法用

**Comment by Lumiaqian** [comment]
> BIOS版本一样吗，BIOS的设置是否已修改？
> 然后在启动参数后面加`-v`看一下是哪里卡住了

已经解决了所有问题，谢谢了

**Comment by 0xHJK** [comment]
可以补充说明一下是怎么解决的吗，给后来者一个参考，谢谢

**Comment by Lumiaqian** [comment]
EFI基本没问题，只是会有一定概率出现卡进度条，但只要加-v就一定不会出现卡进度条，我在其他地方也看见同样的问题和同样的解决办法

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: HJK <notifications@github.com>
发送时间: Tuesday, December 18, 2018 7:09:42 PM
收件人: 0xHJK/XPS13-9360-i5-8250U-macOS
抄送: 曹晶; State change
主题: Re: [0xHJK/XPS13-9360-i5-8250U-macOS] 进不去系统 (#4)


可以补充说明一下是怎么解决的吗，给后来者一个参考，谢谢

―
