### ISSUE TITLE
电池续航问题

### ISSUE THREAD

**Issue by VirgilChen97** [0xHJK/XPS13-9360-i5-8250U-macOS#5]
请问平时使用过程中电池使用时间和发热的情况怎么样呢

**Comment by 0xHJK** [comment]
我没有特地计算过续航时间，但是就我的使用体验而言，并不比我那台mbp短，一般是可以满足日常需求的。也没有明显的发热情况。

不过要注意不能像原生macbook一样合盖就走，合盖之后需要等待一两分钟才能装进包里。如果习惯关机的话，就无所谓。
