### ISSUE TITLE
您好，请问耳机没声音应该怎么解决？

### ISSUE THREAD

**Issue by YipengChen** [0xHJK/XPS13-9360-i5-8250U-macOS#6]

**Comment by 0xHJK** [comment]
参考https://github.com/the-darkvoid/XPS9360-macOS/issues/85#issuecomment-426494719

**Comment by ReVe1uv** [comment]
> 参考[the-darkvoid/XPS9360-macOS#85 (comment)](https://github.com/the-darkvoid/XPS9360-macOS/issues/85#issuecomment-426494719)

请教一下，开机之后苹果logo一出来duang～的一声可以关闭吗？

**Comment by 0xHJK** [comment]
@n1ght2 可以的，电脑设置为静音就没有duang的声音了，和mac一样的

**Comment by 0xHJK** [comment]
更新了耳机声音解决办法，见README.md
