### ISSUE TITLE
内存显示16G(硬件8G), 耳机口时好时坏, bash执行XPS9360会卡死一次

### ISSUE THREAD

**Issue by charlesplus** [0xHJK/XPS13-9360-i5-8250U-macOS#7]
第一次折腾黑苹果, 学过计算机组成原理, 粗略看了一边UEFI原理( http://www.178linux.com/15793 ) 就直接上了车, 非常感谢0xHJK大佬的分享~
装机过程遇到几个小问题, 和大家讨论下, 望能抛砖引玉^_^:
1. 我的本子是XPS 9360 i5-8250u+8+256+1080p, 但是黑苹果后显示16G内存, HWMonitor显示也是16G(莫非机子本来就是16G^_^), 现在还不明白后遗症, 有点担心系统显示不正常会造成内存溢出
2. 耳机口没声音, 删除了/Library/Extensions/AppleHDA_ALC256.kext文件，然后用Kext Wizard程序重建缓存, 但是耳机口依然时好时坏, 看它心情还没摸清规律
3. 我重装过两次, 两次安装过程中运行bash XPS9360.sh 都出现了卡屏的问题

再次谢谢0xHJ大佬的贡献, 没有他我也不敢相信XPS的体验还能这么好~

**Comment by 0xHJK** [comment]
客气啦，我一开始也是学习了别人的分享，写出来也是给别人一个参考，赠人玫瑰手有余香。

内存的问题源自于我一开始参考了别人的配置，对方配置是16G内存，而我的XPS实际内存是8G。但是感觉显示16G比较霸气，也不影响使用，所以我改成8G之后又改回16G，后来传到GitHub之后忘记修改了。如果介意的话，可以用clover configurator修改config.plist。

耳机的问题可以参考这条回复，这里有两个办法选择其中一种：
https://github.com/the-darkvoid/XPS9360-macOS/issues/85#issuecomment-426494719

**Comment by 0xHJK** [comment]
内存显示不一致问题已经解决
