### ISSUE TITLE
请教触摸板的问题

### ISSUE THREAD

**Issue by wongkalok** [0xHJK/XPS13-9360-i5-8250U-macOS#8]
我是使用了黑锅小兵的10.14.2镜像，通过etcher建立u 盘安装文件，替换您提供的所有文件后，进入Mac实用工具后，触摸板无反应，只能使用外接鼠标，并且安装成功后通过安装其他触摸板驱动也无法解决，请教我应该如何解决，急性配置一样，除了没换网卡，麻烦可以解答一下吗？

**Comment by 0xHJK** [comment]
我不确定第三方镜像会不会修改东西。
你可以先重新安装这个触控板驱动试试：https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller

**Comment by wongkalok** [comment]
好的谢谢您，我先尝试一下
