### ISSUE TITLE
求推荐无线网卡Dell DW1560 BCM94352Z淘宝链接

### ISSUE THREAD

**Issue by baihy99** [0xHJK/XPS13-9360-i5-8250U-macOS#9]
求推荐无线网卡Dell DW1560 BCM94352Z淘宝链接，找了好几个店铺都说不支持，不知道买哪个了。
我的机器是xps13 r3609s 8250U 8g版，应该和你的是一样的。谢谢啦

**Comment by 0xHJK** [comment]
我买的是这个：

【BCM94352HMB BCM94352Z DW1560AC双频无线网卡4.0蓝牙 黑苹果MAC】https://m.tb.cn/h.3EUSNA0?sm=8cba34 点击链接，再选择浏览器咑閞；或復·制这段描述￥DXYUbuKYpRW￥后到👉淘♂寳♀👈

仅供参考

**Comment by chenhaoo0** [comment]
这个网卡蓝牙稳定吗，看别人说连耳机和鼠标时断时续的

**Comment by 0xHJK** [comment]
@chenhaoo0 我这里没有出现时断时续的情况，但是系统睡眠之后再打开有时候无法使用蓝牙，需要重启解决。可能不同批次会有点不一样吧。貌似在我告诉店家在黑苹果下的使用方式后，商品就涨价了……

仅供参考吧，如果你发现了更好的也可以提交补充一下
